### PR TITLE
fix: use nvim-treesitter define_modules to attach/detach to buffers

### LINKED ISSUE #41: Show on start doesn't work for the first file opened when opened by telescope
I use https://github.com/nvim-telescope/telescope.nvim for fuzzy file finding.

My nvim-biscuits config is:
```
require('nvim-biscuits').setup({
    cursor_line_only = true,
})
```

After opening neovim, I immediately open the fuzzy finder for telescope and select a file (I've tried *.ts and *.tsx and both are affected) - the biscuits are not displayed.

If I open another file using telescope then the biscuits show as expected.

I did some debugging and found that the `lang` was being determined to be `""` when retrieve from `ts_parsers`.

Happy to provide more info or a video if needed.

### PR DESCRIPTION
**Pull request by dane-harnett**
Fixes #41 

By changing the way nvim-biscuits attaches to the buffer (using the nvim-treesitter define_modules functionality)
it seems to have resolved the issue I was experiencing when opening a file via telescope.

I suspect that the BufEnter autocmd was triggering too early causing the buffer to not complete have been registered with treesitter and so the language was empty string.

### CODE REVIEW

File: lua/nvim-biscuits/init.lua [hunk 1]
```diff
@@ -140,34 +140,15 @@ nvim_biscuits.decorate_nodes = function(bufnr, lang)
     end
 end
 
-nvim_biscuits.setup = function(user_config)
```
Comment (dane-harnett) [inline lua/nvim-biscuits/init.lua:143]: I moved this function below `nvim_biscuits.BufferAttach` definition so that we can use it inside the setup.

File: lua/nvim-biscuits/init.lua [hunk 2]
```diff
@@ -140,34 +140,15 @@ nvim_biscuits.decorate_nodes = function(bufnr, lang)
...
-        final_config = utils.merge_tables(final_config,
-                                          user_config.default_config)
-    end
-
-    utils.clear_log()
-end
-
 local attached_buffers = {}
-nvim_biscuits.BufferAttach = function(bufnr)
-    bufnr = bufnr or vim.api.nvim_get_current_buf()
```
Comment (dane-harnett) [inline lua/nvim-biscuits/init.lua:160]: The `bufnr` should now be passed in.

File: lua/nvim-biscuits/init.lua [hunk 3]
```diff
@@ -140,34 +140,15 @@ nvim_biscuits.decorate_nodes = function(bufnr, lang)
...
+nvim_biscuits.BufferAttach = function(bufnr, lang)
     if attached_buffers[bufnr] then return end
 
     attached_buffers[bufnr] = true
 
-    local lang = ts_parsers.get_buf_lang(bufnr):gsub("-", "")
```
Comment (dane-harnett) [inline lua/nvim-biscuits/init.lua:165]: The `lang` should now be passed in.

File: lua/nvim-biscuits/init.lua [hunk 4]
```diff
@@ -140,34 +140,15 @@ nvim_biscuits.decorate_nodes = function(bufnr, lang)
...
-
     local toggle_keybind = config.get_language_config(final_config, lang,
                                                       "toggle_keybind")
-    if toggle_keybind ~= nil and
-        not config.get_language_config(final_config, lang, "disabled") then
```
Comment (dane-harnett) [inline lua/nvim-biscuits/init.lua:170]: This is now implemented in the `is_supported` function below

File: plugin/nvim-biscuits.vim [hunk 5]
```diff
@@ -2,7 +2,3 @@
 
 highlight default BiscuitColor ctermfg=gray guifg=gray
 
-augroup NVIM_BISCUITS
```
Comment (dane-harnett) [inline plugin/nvim-biscuits.vim:5]: We no longer need this.

**Comment by cmgriffing** [comment]
Awesome. This looks great.
